# Generated by Django 4.2.4 on 2023-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="pizza_image",
            field=models.ImageField(blank=True, upload_to="pizzas/images"),
        ),
    ]
