# Generated by Django 4.2.4 on 2023-08-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0003_pizza_pizza_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="pizza_image",
            field=models.ImageField(blank=True, upload_to="pizzas/media"),
        ),
    ]
